# Generated by Django 5.2.12 on 2026-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateField()),
                ('fecha_creaion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
